### ISSUE TITLE
Get an error when trying to add a record to a integer type BDM

### ISSUE THREAD

**Issue by Arsodora** [Bonitasoft-Community/page_bookmobile#1]
Hi,

I get the following error when I try to add a new record.

ERROR: column "code" is of type integer but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 65
Cause: Sql request have an error
org.postgresql.util.PSQLException: ERROR: column "code" is of type integer but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 65 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120) at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) at org.bonitasoft.custompage.bookmobile.catalog.CatalogModel.executeSqlUpdate(CatalogModel.java:354) at org.bonitasoft.custompage.bookmobile.catalog.CatalogModel.dataInsert(CatalogModel.java:327) at org.bonitasoft.custompage.bookmobile.BookMobileAPI.addData(BookMobileAPI.java:156) at org.bonitasoft.custompage.bookmobile.BookMobileAPI$addData$3.call(Unknown Source) at Actions.doAction(Actions.groovy:162) at Actions$doAction.call(Unknown Source) at Index.doGet(Index.groovy:104) at org.bonitasoft.console.common.server.page.PageRenderer.displayGroovyPage(PageRenderer.java:141) at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:95) at org.bonitasoft.console.common.server.page.PageRenderer.displayCustomPage(PageRenderer.java:61) at org.bonitasoft.livingapps.LivingApplicationPageServlet.doGet(LivingApplicationPageServlet.java:117) at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) at org.bonitasoft.livingapps.LivingApplicationPageServlet.service(LivingApplicationPageServlet.java:80) at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.bonitasoft.console.common.server.filter.CacheFilter.excludePatternFiltering(CacheFilter.java:84) at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:35) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.bonitasoft.console.common.server.login.filter.AuthenticationRule.proceedWithRequest(AuthenticationRule.java:53) at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:119) at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:94) at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.proceedWithFiltering(AuthenticationFilter.java:81) at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:829)
ERROR: column "code" is of type integer but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 65
Consequence: Execution failed
Action: Check the exception

**Comment by pierre-yves-monnet** [comment]
Hello,
Could you upload your BDM somewhere?
or describe the column "code"? What is it? Only an Integer? 
I will check that soon.

**Comment by Arsodora** [comment]
Hi,

Hers is the BDM structure. 

![2021-08-14_11-44-53](https://user-images.githubusercontent.com/59416383/129451762-44ea414e-601a-4936-bbe0-285bae98c57e.jpg)

Dominic

**Comment by Arsodora** [comment]
Hi,

Can I have an update on this issue.

Thanks

Dominic
